name: Kubernetes

on:
  workflow_call: # sempre que algum worflow chamar

jobs:

  EKS: #nome do job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: configurando credenciais da AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ID_CHAVE_ACESSO }}
        aws-secret-access-key: ${{ secrets.CHAVE_SECRETA }}
        aws-region: us-east-2

    - name: clonado repositorio de infra
      run: git clone https://github.com/luiznascimentojr/Infra_CI_Kubernetes.git

    - name: HashiCorp-Setup-Instalando Terraform
      uses: hashicorp/setup-terraform@v2.0.3

    - name: HashiCorp-Iniciando TerraForm 
      run: terraform -chdir=Infra_CI_Kubernetes/env/Homolog init

    - name: HashiCorp-Aprovando o Terraform -Ativo aprovação automatica 
      run: terraform -chdir=Infra_CI_Kubernetes/env/Homolog apply -auto-approve 

    - name: Instalando o Kubectl # utilizado para interagir com o cluster do Kubernetes.
      uses: Azure/setup-kubectl@v3

    - name: Obterndo as configurações necessárias para obtermos a informação no nosso Cluster.
      run: aws sts get-caller-identity
      
    - name: Criando o arquivo kubeconfig do Kubectl com a AWS CLI.      
      run: aws eks update-kubeconfig --region us-west-2 --name homolog2

    - name: Testando a conexão com o Cluster
      run: kubectl get svc

      
